
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-public-key
  namespace: {{ .Release.Namespace }}
data:
  uidam-public-key.pem: {{ .Values.api_gateway.uidam_public_key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-registry.fullname" . }}-database-credentials
  namespace: {{ .Release.Namespace }}
data:
  username: {{ .Values.api_registry.database.username | b64enc | quote }}
  password: {{ .Values.api_registry.database.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-artifactory-credentials
  namespace: {{ .Release.Namespace }}
data:
  artifactory-username: {{ .Values.api_gateway.customPlugins.artifactoryUsername | b64enc | quote }}
  artifactory-password: {{ .Values.api_gateway.customPlugins.artifactoryPassword | b64enc | quote }}
---
{{- if and (.Values.api_gateway.metrics.enabled) (.Values.api_gateway.metrics.datadog.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-datadog-credentials
  namespace: {{ .Release.Namespace }}
data:
  api-key: {{ .Values.api_gateway.metrics.datadog.apiKey | b64enc | quote }}
  application-key: {{ .Values.api_gateway.metrics.datadog.applicationKey | b64enc | quote }}
---
{{- end }}
{{- if and (.Values.api_registry.metrics.enabled) (.Values.api_registry.metrics.datadog.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-registry.fullname" . }}-datadog-credentials
  namespace: {{ .Release.Namespace }}
data:
  api-key: {{ .Values.api_registry.metrics.datadog.apiKey | b64enc | quote }}
  application-key: {{ .Values.api_registry.metrics.datadog.applicationKey | b64enc | quote }}
---
{{- end }}
