
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-int-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "api-gateway.fullname" . }}
    group: api
    facing: internal
    impl: internal
    ms: {{ .Values.ms | quote }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.api_gateway.gateway_port }}
    targetPort: 8080
    name: tcp
  - protocol: TCP
    port: {{ .Values.api_gateway.metrics.port }}
    targetPort: {{ .Values.api_gateway.metrics.port }}
    name: metrics
  type: ClusterIP
  selector:
    app: {{ include "api-gateway.fullname" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "api-gateway.fullname" . }}
    ms: {{ .Values.ms | quote }}
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    path: "{{ .Values.api_gateway.metrics.basePath }}{{ .Values.api_gateway.metrics.prometheus.path }}"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}  
  selector:
    matchLabels:
      app: {{ include "api-gateway.fullname" . }}